# Generated by Django 4.1.6 on 2023-02-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_car_type_alter_car_vin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль'},
        ),
    ]
